export const CART_ACTIONS = {
  SET_IS_CART_OPEN: 'SET_IS_CART_OPEN',
  ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
  CLEAR_FULL_CART_ITEM: 'CLEAR_FULL_CART_ITEM',
  CLEAR_FULL_CART: 'CLEAR_FULL_CART',
};
